### ISSUE TITLE
Track when "security updates" were required

### ISSUE THREAD

**Issue by mattstauffer** [tighten/laravelversions#10]
For example: 
"We discovered a vulnerability in ___ system and so we've patched it in versions 7.1.11, 6.22.14, etc."

That way, if someone passed in a version below that on 7.* or 6.*, they could get a notice that they're vulnerable

**Comment by barryvdh** [comment]
If you want, there are security advisories maintained here: https://github.com/FriendsOfPHP/security-advisories/tree/master/laravel/framework

**Comment by mattstauffer** [comment]
@barryvdh ooooo thank you!
