### ISSUE TITLE
API and web endpoints provide different information.

### ISSUE THREAD

**Issue by jonsugar** [tighten/laravelversions#13]
Visiting the [api endpoint for  version 7.1.14](https://laravelversions.com/api/versions/7.1.14) provides different (more) information than visiting the [web page for  version 7.1.14](https://laravelversions.com/7.1.14)

Maybe this is a duplicate of #8 🤷🏻, it probably has overlaps with #9 as well. 

## API

```json
{
  "data": {
    "major": 7,
    "latest_minor": 30,
    "latest_patch": 4,
    "latest": "7.30.4",
    "is_lts": false,
    "released_at": "2020-03-03T00:00:00.000000Z",
    "ends_bugfixes_at": "2020-10-06T00:00:00.000000Z",
    "ends_securityfixes_at": "2021-03-03T00:00:00.000000Z",
    "status": "security",
    "specific_version": {
      "provided": "7.1.14",
      "needs_patch": true,
      "needs_major_upgrade": false
    },
    "links": [
      {
        "type": "GET",
        "rel": "major",
        "href": "https:\/\/laravelversions.com\/api\/versions\/7"
      },
      {
        "type": "GET",
        "rel": "self",
        "href": "https:\/\/laravelversions.com\/api\/versions\/7.1.14"
      },
      {
        "type": "GET",
        "rel": "latest",
        "href": "https:\/\/laravelversions.com\/api\/versions\/7.30.4"
      }
    ]
  }
}
```

## Web Page

![image](https://user-images.githubusercontent.com/1974648/105859736-c78cae80-5fe4-11eb-8299-cb9694a2fa4f.png)

**Comment by mattstauffer** [comment]
@jonsugar Ahhh--I forgot to trigger a page-cache refresh after syncing the data down, so that `7.0.0` gets cached and not refreshed for a day. My bad! Overly aggressive caching.

**Comment by mattstauffer** [comment]
And we're working on a design update that would make this information available on the web page:
![image](https://user-images.githubusercontent.com/151829/105864847-59ce8b80-5fc0-11eb-96b1-98260e89c8fc.png)

**Comment by jonsugar** [comment]
Answered and closed before I even finished editing the description 🤣

**Comment by mattstauffer** [comment]
@jonsugar 😆
