### ISSUE TITLE
Possibility of translation

### ISSUE THREAD

**Issue by olsza** [tighten/laravelversions#19]
We could rewrite the texts to e.g. JSON and use the translation function in the code, and then add the possibility to switch to the selected language

**Comment by mattstauffer** [comment]
That's fine by me! We built a translation system in Onramp (github.com/tighten/onramp) so we can pull the JavaScript over from that

**Comment by olsza** [comment]
hay @mattstauffer, currently I have it locally made, but I use the akaunting/language package, and I can see that in the tighten/onramp project you use kg-bot/laravel-localization-to-vue, and here in the larave version project there is currently no VUE.
Are you planning to use VUE in this project? because I'm not good at this yet :/

**Comment by mattstauffer** [comment]
Hey @olsza! Thanks for asking, and no worries.

Because this project doesn't have Vue, we don't even need to worry about a package at all; we can use Laravel's built-in translation and leave it at that. I'm glad you took a look at Onramp, because it's a great reference point; take a look at how translations are handled there, ignore the Vue package, and then we'll be good to go! I can just re-build the language switcher in Alpine.

**Comment by olsza** [comment]
maybe I will manage to publish a branch with languages by Tuesday (en and pl) but with the possibility of adding other languages ;)
but because during testing I noticed that e.g. models used url instead of route + name route, so it takes me a little longer and I only do it after working hours.
in addition, I set it so as not to spoil SEO and leave it as it is, i.e. by default, the English language will be without the prefix, with the en prefix transfer to without the prefix, in other languages to leave language prefixes

ps. I will not use any of the additional packages, however, as I wrote earlier, because every package I checked works on leaving a prefix with the language code in the address, and I wanted to keep the current state for SEO, so I wrote my middleware so that there was no prefix for EN ;)

**Comment by olsza** [comment]
I added PR #22 ,
please CR

**Comment by olsza** [comment]
How does it look locally with flags, translations:

![pl](https://user-images.githubusercontent.com/12556170/107492706-0c8c1580-6b8d-11eb-9d45-349fdf5865a9.png)
![en](https://user-images.githubusercontent.com/12556170/107492715-0dbd4280-6b8d-11eb-8a6c-1534ee5c619d.png)
![en9](https://user-images.githubusercontent.com/12556170/107492719-0e55d900-6b8d-11eb-8054-5ffc6b5ca27a.png)
![pl9](https://user-images.githubusercontent.com/12556170/107492721-0eee6f80-6b8d-11eb-99de-9de324dc72fb.png)

**Comment by olsza** [comment]
Current view instead of flags are the names of the available translations.
I hope that PR will be accepted soon :)

![Zrzut ekranu z 2021-02-17 18-28-25](https://user-images.githubusercontent.com/12556170/108532537-3c978f00-72d8-11eb-854f-fb064af91d4b.png)
