### ISSUE TITLE
Enhancement - JSON extension on version entity

### ISSUE THREAD

**Issue by SecondeJK** [tighten/laravelversions#21]
This is an enhancement request for a feature that mirrors how Shopify implements it's API for entities.

Example:

https://laravelversions.com/8
Gives the page back for the version.

https://laravelversions.com/8.json
Gives the version entity back as a json object, similar to how the https://laravelversions.com/api/versions endpoint looks.

I can issue a PR to do this enhancement if the maintainers approve of it.

**Comment by mattstauffer** [comment]
@SecondeJK I think that's a great idea! I would only be curious: do we maintain _both_?

**Comment by SecondeJK** [comment]
Urgh, now that IS a question. The thing is, the way I believe you can code it in Laravel is to just let the route switch up resources - if that's the case then it's pretty low maintainence. BUT at the same time, it won't fall into the API versioning so probably wouldn't make much sense.

**Comment by mattstauffer** [comment]
Yup. It's easy to do, but once you already have a defined `api` route like we do here, it doesn't make as much sense.

**Comment by SecondeJK** [comment]
I'm going to close this as yeah, it doesn't really make much sense to do this when the API is being versioned. I got a bit overexcited!
