### ISSUE TITLE
Design tweaks

### ISSUE THREAD

**Issue by mattstauffer** [tighten/laravelversions#24]
- Make header link light blue
- Update the colors of the badges/labels to be exact
- Update the tables to use grey lines, not black, like in the designs
- Update the table headers to use the right color text
- Updater the table text content to use the right color text

(These are all comparing against this design; https://user-images.githubusercontent.com/151829/106034455-f0727980-60a0-11eb-9500-b73870f1ee10.png. let me know if nohemi changed things since i output that design)

**Comment by MarcyLina** [comment]
**- Make header link light blue**
Can you screenshot what you see? I am viewing it as light blue
![Screen Shot 2021-02-22 at 10 59 31 AM](https://user-images.githubusercontent.com/32626323/108742207-1868c780-74fd-11eb-9a57-c4431b6181cb.png)

**- Update the colors of the badges/labels to be exact**
The color palette I used was pulled directly from sketch
<img width="155" alt="Screen Shot 2021-02-22 at 10 39 18 AM" src="https://user-images.githubusercontent.com/32626323/108739417-3ed93380-74fa-11eb-9ce7-7275b17caa30.png">

**- Update the tables to use grey lines, not black, like in the designs**
Done!

**- Update the table headers to use the right color text**
Done!

**- Updater the table text content to use the right color text**
-Done!

**Comment by mattstauffer** [comment]
![image](https://user-images.githubusercontent.com/151829/108748252-5e795780-750c-11eb-9692-c6c52f32f85f.png)

This is what I see on Firefox. and Chrome.

Those colors look right now. Not sure what version I was looking at that was wrong 🤷🏻‍♂️

**Comment by mattstauffer** [comment]
I see you have text-blue-800 in there.. is this maybe a PurgeCSS bug? That's weird!

**Comment by MarcyLina** [comment]
@mattstauffer That's so weird! I dont have a blue-800 in my palette:
![image](https://user-images.githubusercontent.com/32626323/108748973-d479c080-7504-11eb-8a8d-d9cb9d91d80a.png)

**Comment by MarcyLina** [comment]
OK so it looks like the blue-800 was for links from the old code. (footer, for example) The palette in sketch doesn't address a dark blue so do you want me to define it as using the standard TW palette? I could also just leave it black and remove the blue-800 classes.

**Comment by vmartuniyk** [comment]
The letter " n " looks very strange in the logo. This is a font type or just a bug?
![Bug on logo](https://user-images.githubusercontent.com/13577787/109398444-a7cf0a00-7945-11eb-8f1e-b59250218148.png)

**Comment by mattstauffer** [comment]
@vmartuniyk I'm guessing our designer did all of the lettering herself, and she intentionally squared much of it off; you can see the same in the `r` and the `l`.
