### ISSUE TITLE
Status Texts should be translatable too

### ISSUE THREAD

**Issue by wilsenhc** [tighten/laravelversions#35]
This makes for a weird reading experience, mixing English abbreviations with other languages (ALL, FUT, SEC, EOL).

These texts should be added to the Translation keys too.

**Comment by olsza** [comment]
Therefore, the colors Green, Yellow, Red and Blue are added.

**Comment by wilsenhc** [comment]
Not sure about colors, since they would mean the same no matter what the language. 
But the abbreviations for the Statuses should be localized too.

@mattstauffer What do you think abotu this idea?

Later today I'll work on making a PR to this
