### ISSUE TITLE
Version moves away from "Currently supported versions" on its last day of support, instead of the day after support ends

### ISSUE THREAD

**Issue by olsza** [tighten/laravelversions#48]
I think, as it is March 3, 2021 and the support is TILL March 3, 2021, it should be on the list that is still supported, not the end of support, do I understand?

I do not know if this is a bug that I should correct and add tests ;)
I like it when it is perfect ;p

![Zrzut ekranu z 2021-03-03 18-55-53](https://user-images.githubusercontent.com/12556170/109850602-fa186f80-7c52-11eb-8f3d-073a3f768e22.png)

**Comment by mattstauffer** [comment]
@olsza I think you're right! Looks like I used a < when I should've used <=
