### ISSUE TITLE
Come up with a better layout for the "show" page

### ISSUE THREAD

**Issue by mattstauffer** [tighten/laravelversions#8]
![image](https://user-images.githubusercontent.com/151829/105620491-c3397900-5dcb-11eb-9e18-c9f41582f7bb.png)

This ain't it.

**Comment by mattstauffer** [comment]
Nohemi, our designer at Tighten, is working on this! 🙌

**Comment by ihtishamKhan** [comment]
@mattstauffer  Can I team up with him?

**Comment by mattstauffer** [comment]
@ihtishamKhan Hey, Nohemi is a woman, and she'll be sharing her designs as she builds them--is there anything in particular you want to work with her on?

**Comment by mattstauffer** [comment]
![laravel-versions-show](https://user-images.githubusercontent.com/151829/106034447-efd9e300-60a0-11eb-8ec1-c59b37b55119.png)
![laravel-versions-index](https://user-images.githubusercontent.com/151829/106034455-f0727980-60a0-11eb-9500-b73870f1ee10.png)

**Comment by mattstauffer** [comment]
I'm starting a branch right now to build out this simple re-skin.

**Comment by ihtishamKhan** [comment]
@mattstauffer wanted to build with others so I can learn something new, I mostly work with backend in Laravel

**Comment by mattstauffer** [comment]
Update to add "Future"
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/151829/106343367-fae46d00-6272-11eb-876c-ba4e7c1a42af.png">

**Comment by mattstauffer** [comment]
Assets:
https://up.stauffe.red/yAu6jxOb

**Comment by mattstauffer** [comment]
Colors:

#5AC984
#F2D987
#DE8888
#75B5E2

**Comment by olsza** [comment]
Where can I find a branch with this view layout, because maybe I can first see how to add languages there...
General, I think I like this view better

**Comment by mattstauffer** [comment]
@olsza I haven't made much progress. If you want to add languages you can either wait until I finish it or just add it before hand, your call.

**Comment by olsza** [comment]
Hay @mattstauffer 
I noticed the front is tailwind where i am not very good at it.
I think it's better to check what I did #22 and if it's ok then this code can be based on. As you wrote yourself that "I haven't made much progress" it is better to base on mine, of course if the code is ok, because there are some changes.
