### ISSUE TITLE
Incorrect release date for Laravel 9

### ISSUE THREAD

**Issue by jorqensen** [tighten/laravelversions#89]
Laravel 9 is unfortunately postponed, but this does not reflect on Laravel Versions.

Doesn't matter too much now, but in the future it would be nice to be able to look back and see the actual release date. :sweat_smile:

**Comment by mattstauffer** [comment]
We just fixed it in https://github.com/tighten/laravelversions/commit/3695cf9141a3719110228274bcfc8560d20bf539, thanks so much for the issue!
